# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				panda = true
				axolotl = true
				cow = true
				chest_minecart = true
				tropical_fish = true
				pig = true
				slime = true
				skeleton = true
				bat = true
				zombie = true
				drowned = true
				sheep = true
				player = true
				dolphin = true
				pufferfish = true
				item = true
				turtle = true
				salmon = true
				glow_squid = true
				cod = true
				witch = true
				glow_item_frame = false
				squid = true
				spider = true
				parrot = true
				creeper = true
				enderman = true
				cat = true
				armor_stand = true
				horse = true
				wolf = true
				iron_golem = true
				bee = true
				cave_spider = true
				item_frame = true
				painting = true
				ocelot = true
				arrow = true
				rabbit = true
				polar_bear = true
				experience_orb = true
				stray = true
				donkey = true
				wandering_trader = true
				husk = true
				lightning_bolt = true
				elder_guardian = true
				guardian = true
				firework_rocket = true
				fox = true
				strider = true
				zombified_piglin = true
				piglin = true
				ghast = true
				experience_bottle = true
				goat = true
				ravager = true
				pillager = true
				trader_llama = true
				wither_skeleton = true
				egg = true

			[light_sources.settings.entities.terrarianslimes]
				black_slime = true
				green_slime = true
				jungle_slime = true
				red_slime = true
				yellow_slime = true
				mother_slime = true
				blue_slime = true
				umbrella_slime = true
				ice_slime = true
				spiked_ice_slime = true
				sand_slime = true
				spiked_jungle_slime = true
				purple_slime = true
				lava_slime = true
				pinky = true
				dynamite = true

			[light_sources.settings.entities.more_babies]
				skeleton = true
				dolphin = true
				bat = true
				salmon = true
				glow_squid = true
				squid = true
				spider = true
				parrot = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.ecologics]
				squirrel = true
				coconut_crab = true

			[light_sources.settings.entities.valley]
				duck = true
				fire_eel = true
				minnow = true
				perch = true
				sardine = true

			[light_sources.settings.entities.mca]
				male_zombie_villager = true
				female_zombie_villager = true
				female_villager = true
				male_villager = true

			[light_sources.settings.entities.dinocraft]
				chinlea = true
				theropod = true
				sauropod = true
				mosasaurus = true
				deinonychus = true
				troodon = true
				stegoraptor = true

			[light_sources.settings.entities.adventurez]
				amethyst_golem = true
				deer = true
				summoner = true
				iguana = true
				skeleton_vanguard = true
				mammoth = true
				necromancer = true
				wither_puppet = true
				orc = true
				nightmare = true

			[light_sources.settings.entities.alaskanativecraft]
				harp_seal = true
				ptarmigan = true
				moose = true
				dogsled = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				mauler = true
				glare = true
				moobloom = true
				iceologer = true

			[light_sources.settings.entities.automobility]
				automobile = true

			[light_sources.settings.entities.creatures_of_the_snow]
				snow_seal = true
				snow_trover = true
				penguin = true
				snikerbosh = true
				beluga = true
				narwhal = true

			[light_sources.settings.entities.tinyskeletons]
				baby_skeleton = true

			[light_sources.settings.entities.aqupd]
				grizzly_bear = true

			[light_sources.settings.entities.levelz]
				level_experience_orb = true

			[light_sources.settings.entities.brazier]
				crazed = true

			[light_sources.settings.entities.immersive_portals]
				loading_indicator = true
				nether_portal_new = true

			[light_sources.settings.entities.capybara]
				capybara = true

			[light_sources.settings.entities.origins]
				enderian_pearl = true

			[light_sources.settings.entities.moretotems]
				summoned_bee = true
				summoned_zombie = true

			[light_sources.settings.entities.direbats]
				direbat = true

			[light_sources.settings.entities.ratsmischief]
				rat = true

			[light_sources.settings.entities.earthtojavamobs]
				albino_cow = true
				cookie_cow = true
				amber_chicken = true
				bold_striped_rabbit = true
				bone_spider = true
				inky_sheep = true
				jolly_llama = true
				cluckshroom = true
				wooly_cow = true
				sunset_cow = true
				sooty_pig = true
				rainbow_sheep = true

			[light_sources.settings.entities.naturalist]
				vulture = true
				bluejay = true
				bear = true
				firefly = true
				snail = true
				butterfly = true
				snake = true
				robin = true
				coral_snake = true
				zebra = true
				lion = true
				cardinal = true
				boar = true
				rhino = true
				elephant = true
				rattlesnake = true
				deer = true
				canary = true

			[light_sources.settings.entities.immersive_aircraft]
				gyrodyne = true
				biplane = true

			[light_sources.settings.entities.hoverpets]
				blaze_pet = true

			[light_sources.settings.entities.ants]
				black_ant = true
				red_ant = true
				brown_ant = true

			[light_sources.settings.entities.sit]
				entity_sit = true

