permissions = [
   #  All permissions for Taterzens mod commands.
   #  Will be active only if LuckPerms is installed.
   #  These values are not editable, they're here to inform you.

   #  Permissions for managing the mod itself. 
   #  Gets the link for the wiki.
   "taterzens.wiki_info",
   #  Enables editing Taterzens config in-game.
   "taterzens.config.edit",
   "taterzens.config.edit.language",
   #  Enables reloading the config file.
   "taterzens.config.reload",


   #  Permissions for managing Taterzens.
   "taterzens.npc",
   #  Handles Taterzen creation.
   "taterzens.npc.create",

   #  Selecting Taterzens
   #  Selects Taterzen (in front of the executor).
   "taterzens.npc.select",

   # Enables selecting taterzen even if it's locked
   "taterzens.npc.select.bypass",
   #  Selects Taterzens by ID.
   "taterzens.npc.select.id",
   #  Deselects Taterzen.
   "taterzens.npc.select.deselect",
   #  Lists Taterzens.
   "taterzens.npc.list",
   #  Removes Taterzen.
   "taterzens.npc.remove",
   #  Save Taterzen to a preset file.
   "taterzens.npc.preset.save",
   #  Load Taterzen from a preset file.
   "taterzens.npc.preset.load",
   #  Teleport Taterzen to a given location.
   "taterzens.npc.tp",


   #  Editing Taterzens
   #  Edit Taterzen's name.
   "taterzens.npc.edit.name",

   #  Editing Taterzen's commands

   # Editing command cooldown
   "taterzens.edit.commands.cooldown",
   "taterzens.edit.commands.cooldown.set",
   "taterzens.edit.commands.cooldown.edit_cooldown",
   #  Manages permission level of Taterzen.
   "taterzens.npc.edit.commands.set_permission_level",
   #  Removes command by ID from Taterzen.
   "taterzens.npc.edit.commands.remove",
   #  Add command to Taterzen.
   "taterzens.npc.edit.commands.add",
   # Allows adding bungee commands (e.g. /server)
   "taterzens.npc.edit.commands.addBungee",
   #  Clears all commands of Taterzen.
   "taterzens.npc.edit.commands.clear",
   #  List commands Taterzen.
   "taterzens.npc.edit.commands.list",

   #  Changes Taterzen's type to other entity type
   "taterzens.npc.edit.entity_type",
   #  Enters path edit mode for Taterzen.
   "taterzens.npc.edit.path",
   #  Clears Taterzen's path.
   "taterzens.npc.edit.path.clear",

   #  Editing Taterzen's messages
   #  Enters message adding mode of Taterzen.
   "taterzens.npc.edit.messages",
   #  Clears all the messages of Taterzen.
   "taterzens.npc.edit.messages.clear",
   #  Lists all the messages of Taterzen.
   "taterzens.npc.edit.messages.list",
   #  Deletes Taterzen's message by ID.
   "taterzens.npc.edit.messages.delete",
   #  Edits delay of the message by ID.
   "taterzens.npc.edit.messages.delay",
   #  Enables editing selected message.
   "taterzens.npc.edit.messages.edit",
   # Enables message swapping
   "taterzens.npc.edit.messages.swap",
   # Allows total control of messages within gui
   "taterzens.npc.edit.messages.reorder",
   #  Enables changing Taterzen's skin.
   "taterzens.npc.edit.skin",
   #  Enables changing Taterzen's equipment.
   "taterzens.npc.edit.equipment",
   # Enables editing whether Taterzen should drop equipment
   # on death (not when removed using `/npc remove`)
   "taterzens.npc.edit.equipment.drops",
   #  Enables editing Taterzen's movement.
   "taterzens.npc.edit.movement",
   # Follow movement permission
   "taterzens.npc.edit.movement.follow",

   #  Enables editing Taterzen's behaviour.
   "taterzens.npc.edit.behaviour",

   #  Enables editing Taterzen's tags.
   "taterzens.npc.edit.tags",
   #  Enables changing whether Taterzen can be leashed.
   "taterzens.npc.edit.tags.leashable",
   #  Enables changing whether Taterzen can be taken away with boats / minecarts.
   "taterzens.npc.edit.tags.allow_riding",
   #  Enables changing whether Taterzen is pushable.
   "taterzens.npc.edit.tags.pushable",
   #  Enables changing whether Taterzen should jump during attacking.
   "taterzens.npc.edit.tags.jump_while_attacking",
   # Whether Taterzen's name can be shown like it's sneaking
   "taterzens.npc.edit.tags.sneakNameType",
   # Whether Taterzen should make sounds
   "taterzens.npc.edit.tags.allow_sounds",
   #  Allows editing Taterzen's professions.
   "taterzens.npc.edit.professions",
   #  Enables adding profession.
   "taterzens.npc.edit.professions.add",
   #  Enables removing profession.
   "taterzens.npc.edit.professions.remove",
   #  Enables listing Taterzen's professions.
   "taterzens.npc.edit.professions.list",
   # Enables editing Taterzen's pose
   "taterzens.npc.edit.pose",
   # Enables editing Taterzen's vehicle
   "taterzens.npc.edit.mount",

   # Enables providing an action to Taterzen
   # Going to block position
   "taterzens.npc.action.goto",
   # Interacting with block
   "taterzens.npc.action.interact",

   # Permissions for `/profession` command
   "taterzens.profession",
   "taterzens.profession.scarpet",
   "taterzens.profession.scarpet.add",
   "taterzens.profession.scarpet.remove"
]
